language: python

python:
- '3.4'
- '3.5'

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.6
      script: travis_retry coverage run -m pytest && coveralls

install:
- pip install masonite_cli
- pip install -e .
- pip install -r requirements.txt

script: travis_retry coverage run -m pytest

deploy:
  provider: pypi
  user: josephmancuso
  password:
    secure: McIrYxinFbhhTQMmWt+IW6nGstz41+j87iUJ4ovVqxpAirsm7gZ75AoUJ1UAoa/y9uWxvR0ZzBjuhnt04mxPr3XZ4X8qCm/boWtHE3WDt4Kd/Xw4hVJ8rMUBTGqWJ1s1MRRXHkUYsACDEqJvJ2mAvp9yLGeXDWlgfQa/7Fd6zQV1V9FaxeyjkLw4efOXXL30pUyaRrJMLzeHhNp2/Kv+4VYGh+7TnbQOJlCV2HNuDdTmetIfT7VJDhw1mpY2Shdo4cIWkJ6ANxG1CIQh/Bm2mKjSRliKviydfizzgJw9EDR0kvogYUZYeFt9DWAJmdcEP+PamkEMW9L6q6O1268BcoID3/Bu02SoMvn1wWZgWL+HoTB1Jr+fc6nAveFRSCio2tRVUaQ+tylwX6la8198JZBBZc+1AYLZQpcaMy2W03y6oYtOb1KZv0IPG49Dxfk/+OnPGb7TEPiummRN1vKSB+wURKDHVhZhGuons/vW3/PrKsDtbyw/I4AVXt+rKZFt30qies0vjvPR55z0g2t/sV+Pei6cBTstBYgcjNqpFIjIOXjJgmm7asfUC5E36+hVb5BxLAvMbBU4s77qpmG6h0XKueoWhmI3gUltDyPNZXFrDVyU/KYRjocWa7bVAr3vryuMc9IModDNvwFq/nnkaYLD3jvxu7DdMjhi90KWit8=
  on:
    tags: true
    python: 3.6
