version: 2
jobs: 
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: pip install https://github.com/$BUILD_REPO/archive/$BUILD_BRANCH.zip --user
      - run: pip install -e . --user
      - run: pip install -r requirements.txt --user
      - run: python -m pytest
